name: Main test

on:
  pull_request:
    branches: [ "master" ]
    paths:
      - "StringUtils/**"
  push:
    branches: ["StringUtils"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn test